config:
  pipelines:
    - name: firstETL
      metadata: 
        name: nombre test
        tag: first tag
      steps:
        extract:
          - name: postgres_local
            type: postgres
            query: SELECT * FROM public.test
          - name: postgres_local2
            type: postgres
            query: SELECT 1 as A FROM public.test
